### ISSUE TITLE
Remove page markers and pre-chapter whitespace

### ISSUE THREAD

**Issue by sdfg2** [foobnix/LirbiReader#111]
Hello,

First, fantastic software, I've been looking for a replacement for the ageing MoonReader and I switched within ten minutes of finding things.  I am very impressed.

The biggest thing that impressed me was true auto-scroll, not 'get to the end of the chapter and move to the next one' auto-scroll that MoonReader has.  Now I'd like to make my reading experience truly 21st century and get rid of any distractions when reading.  I don't know CSS that well (I don't even know if it is a CSS thing or not) but is there a way to remove page markers, and get rid of any whitespace between the end of one chapter and the start of another?

**Comment by foobnix** [comment]
>but is there a way to remove page markers, and get rid of any whitespace between the end of one chapter and the start of another?
Yes, everything is possible :)
Please attache the book example and screenshot what whitespace do you want to delete.

**Comment by sdfg2** [comment]
Found and example with a book from Gutenberg: https://www.gutenberg.org/ebooks/1342.epub.images?session_id=441c83358211fcb7990143be2be09d11717b314d

![screenshot_20180309-100940](https://user-images.githubusercontent.com/5736478/37202605-e3ceefbe-2382-11e8-84ea-5e028be3af0a.png)

That's a good example of both the line and the whitespace.

**Comment by foobnix** [comment]
Sorry, it's not possible to change simply (you can search how to modify MUPDF do display epub without page break)
You can open html or txt book and it's should be without page breaks.
