### ISSUE TITLE
Bug: forever loading upon opening

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#12]
I am experiencing this (in real time) on Librera beta 7.0.56, on the Onyx Boox Max Carta (Android 4.0.4). (At the moment  cannot test the new beta, being away bound on mobile)
On last boot session, I was reading a 150MB (made of scans) PDF; having booted the device today, 
-- when I open Librera, it tries to load the last book but hangs forever in "Loading..Please wait"; 
-- so I open a new book from the launcher, but still hangs forever in "Loading..Please wait". 

I am not sure how can I further assess

**Comment by m-dp** [comment]
Opening a former version (before installing, I change the package name to e.g. com.foobnix.pdf.beta7056, so I can have more versions installed), I was then (strangely) able to open again 7.0.56, displaying the tabber screen instead of trying to open books. 

A strange thing: the "Open last book" checkbox was unset

**Comment by foobnix** [comment]
please verify in 7.1.4

**Comment by m-dp** [comment]
As soon as possible; I am unfortunately away from instruments at the moment

**Comment by m-dp** [comment]
As soon as possible; I am unfortunately away from instruments at the moment

**Comment by foobnix** [comment]
is it problem still exists?

**Comment by m-dp** [comment]
I have the 7.1.6 on my tablets and I will test extensively this evening and tomorrow
