### ISSUE TITLE
Center on screen button

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#15]
I missed this everytime I moved the pages by accidental panning, having forgotten to "lock position": 
it would be nice to have the option to re-center the pages on the screen. 

You could combine this option with the "(zoom) fit to screen" in easy mode; when scrolling pages (advanced mode) the two options of "centering" and "fit to screen" should be separate

**Comment by foobnix** [comment]
I think centering and fit to screen is the same for easy mode.
Now it's implemented.
