### ISSUE TITLE
Disable animation on slow refresh screens

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#16]
Animation in general - "Simple scroll animation" in the preferences - should be disabled by default on slow refresh screens. 
This is first of all for electrophoretic displays. 
The one I have here shows a refresh rate in 'dumpsys' of 0.001, which is far from true; so-called 'A2' mode looks around 8fps, and I have seen videos of new EPD screens that look capable of around 16fps. 
Probably, a display with a rate below 20fps could be considered "slow" (?). 
The point is especially important for EPD display: pixel switchi in normal mode is graphically messy and uses battery inefficiently in animations

**Comment by foobnix** [comment]
Yes it's possible but I don't know how to detect screen type programmatically.

**Comment by m-dp** [comment]
It should be 
getDefaultDisplay().getRefreshRate();
You already have that "Default Display" stored in some variable, I think I remember

**Comment by m-dp** [comment]
To get the screen type is more difficult, but to get the refresh is easier. 
Hence, 
if refr<20 { disable_anim(); }

**Comment by m-dp** [comment]
To get the screen type is more difficult, but to get the refresh is easier. 
Hence, 
if refr<20 { disable_anim(); }

**Comment by foobnix** [comment]
Thank you for help, will be in the 7.1.6 build

**Comment by m-dp** [comment]
Hello, 
it seems that "simple scroll animation" does not actually disable the animation. Actually, I see no difference, with or without it, on PDF or EPUB, on LED or EPD. 

Could there be a way to turn the page without animation?

**Comment by m-dp** [comment]
Sorry, my fault: I confused swipe and side-tap to change page. On side-tap, the "simple screen animation" works correctly.
