### ISSUE TITLE
Add mode selection in the "Starred" documents browsing tab

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#17]
It would be very useful (and consistent with the other documents browsing tabs) to have the mode selector (MODE_LIST, MODE_LIST_COMPACT, MODE_GRID, MODE_COVERS) also in the "Starred" documents browsing tab. 

Thanks!

**Comment by foobnix** [comment]
Please verity in beta

9 сент. 2017 г. 9:24 пользователь "m-dp" <notifications@github.com> написал:
