### ISSUE TITLE
Multi-document

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#18]
I am seeing, discussing in forums, that many users on mobile devices are missing simultaneous browsing of many documents, which they would do on desktops (multi-window or multi-tabs). 
It is like multi-tab browsing on Web browsers. 
Do you think it can be done? 

(Apologies for any delay, I am currently away)

**Comment by foobnix** [comment]
yes, it is good idea but app design not allow it. need to re implement logic to works with multi docs at the same time. Maybe in the future.
