### ISSUE TITLE
Missing TOC in documents 

### ISSUE THREAD

**Issue by simonbellu** [foobnix/LirbiReader#19]
I suggest to disable the toc icon in documents with no toc. Instead of opening a blank toc window (and closing it), could be showed a toast to inform that the document has no toc. The toc icon could be disabled and with a different color (grey) to be clear it is disabled.

**Comment by foobnix** [comment]
Please attache some doc with missing TOC

13 сент. 2017 г. 15:20 пользователь "simonbellu" <notifications@github.com>
написал:

**Comment by simonbellu** [comment]
[Purcell - Suite in G minor, Z660.pdf](https://github.com/foobnix/LirbiReader/files/1299402/Purcell.-.Suite.in.G.minor.Z660.pdf)

**Comment by foobnix** [comment]
fixed in 7.1.30
