### ISSUE TITLE
Ads in the program

### ISSUE THREAD

**Issue by loopinghole** [foobnix/LirbiReader#2]
Librera seems nice, but there are some unpleasant advertisement banners in it. They should be removed.

Also, while I am not a lawyer, it does seem to me that the license should be AGPL instead of GPL, since you are using muPDF, which is AGPL-licensed.

**Comment by foobnix** [comment]
GPL and banners are not conflicting. You can buy PRO or use Beta without banners. Even more, if you buy PRO all Librera apps will be without banners.

yes MuPDF is AGPL, but GPL licence allow to be GPL or AGPL for the project using AGPL.

**Comment by licaon-kter** [comment]
@foobnix reading https://mupdf.com/docs/android-library.html
> you may not use any proprietary closed source libraries or components in your app. This includes (but is not limited to) Google Play Services, Google Mobile Services, AdMob by Google, Crashlytics, Answers, etc. 

It means that you've acquired a "Commercial license" for mupdf for Play version? eg. https://github.com/foobnix/LibreraReader/blob/master/app/build.gradle#L365
