### ISSUE TITLE
Icon for "fit and centre" - glyphicons_488_fit_image_to_frame

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#24]
As the icon for the "fit and centre" operation, more precisely ImageView ID "@+id/moveCenter", I think that glyphicons_114_justify does not suggest the operation immediately. 
On the other hand, I think that glyphicons_488_fit_image_to_frame is almost perfect (this already existing icon is very similar to what I was thinking to draw and propose instead of glyphicons_114_justify).

**Comment by foobnix** [comment]
fixed in beta
