### ISSUE TITLE
Error in Shell Script

### ISSUE THREAD

**Issue by betamaxtelecom** [foobnix/LirbiReader#26]
Hello i am getting a error in this file update_all.sh
Error in line number 22 this is output of this command 
root@pentest:/home/poseidon/atman/LirbiReader# sudo ./update_all.sh 
fatal: destination path 'google-play-services-ads' already exists and is not an empty directory.
./update_all.sh: 22: ./update_all.sh: [[: not found
Please help me i reviewed the file and i think that exist a issue in this line 
for d in * ; do
if [[ -d $d ]]; then
    echo "$d"
    rm $d/build.xml
The shell script not are working please help me 
Thanks

**Comment by foobnix** [comment]
try ./remove_all.sh to delete existed folders and then ./update_all.sh
