### ISSUE TITLE
Feature request: contrast

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#27]
Greetings, 
some documents (especially scanned documents) may not be fully contrasted, ranging as images from light grey to darker grey instead of white to black. 
It would be nice to have a contrast enhancer, to render the pages flattening colours towards the extremities of black and white. Example curves: 
![contrast](https://user-images.githubusercontent.com/11769458/31188309-c728c9de-a934-11e7-849b-d2b035d099b6.png)

This is especially useful on EPD displays, where you really have "light grey to dark grey" in reality - some contrast is lost because of the current hard limits of the technology...

**Comment by foobnix** [comment]
Please assign some documents for better understand the problem

**Comment by foobnix** [comment]
try in beta command "@@contrast" (enter to the search field) works only in Easy Mode
![screenshot from 2017-10-04 21-49-20](https://user-images.githubusercontent.com/432440/31193876-fd21a128-a94d-11e7-9d82-b69fd6ed4f30.png)
0 - no contrast

**Comment by m-dp** [comment]
Sorry, I cannot get the dialogue: 
What I do: * open document; * show Librera top bar and bottom bar; * tap on "magnifying lens (search)" icon in the bottom left; * type '@@contrast' in the field, literal from first "@" to last 't' just like the strings in /com/foobnix/ui2/fragment/SearchFragment2.java ; * press the "magnifying lens (search)" button, which stands for "enter", right to the search field: 
the field actually searches for the string '@@contrast' in the document, I was expecting that to show the "Contrast" dialogue. What am I doing wrong?

**Comment by foobnix** [comment]
try here 
![screenshot from 2017-10-05 00-13-43](https://user-images.githubusercontent.com/432440/31200056-2413cc48-a962-11e7-9b3f-7ed3738516d1.png)

**Comment by foobnix** [comment]
test features I do not add it to the main UI
In the feature if you test it and like it I can make contrast individual for every document

**Comment by m-dp** [comment]
It works, and well, but it seems that it slows page rendering a lot. And after changing a few pages, the application crashed (image of a book cover with '#crash' as a title). I'll continue checking.

**Comment by m-dp** [comment]
Maybe the code needs a bit of extra speed, but I can confirm: the contrast option it's very useful. It changes readability of some documents dramatically. 

Maybe the code can be made speedier like this: 
* instead of having a full contrast control, you only have a checkbox "high contrast mode";
* the operation, instead of being `R = (int) (((((R / 255.0) - 0.5) * contrast) + 0.5) * 255.0);` could be `R = (R<<1)-128` (plus the conditional for the thresholds, already there, `if (R < 0) {R = 0;} else if (R > 255) {R = 255;}`;
* and maybe only red is sampled, so the pixels is assigned instead of `bmOut.setPixel(x, y, Color.rgb(R, G, B));` as `bmOut.setPixel(x, y, Color.rgb(R, R, R));`

Note: in /com/foobnix/pdf/info/wrapper/MagicHelper.java
I see in lines 736, 744 and 752: 
R = Color.red(pixel);
G = Color.red(pixel);
B = Color.red(pixel);
but was it meant to be instead
R = Color.red(pixel);
G = Color.green(pixel);
B = Color.blue(pixel);
?

**Comment by m-dp** [comment]
Ok I tested my suggestions this morning. There is a problem. 
While useful and something that one may wish, `public static Bitmap createContrast(Bitmap src, double value)` is too slow. On the devices that would really benefit it - EPD devices, unfortunately currently "battery conservative (= slow)" -, the function takes around 10 seconds. 
It is not a matter of the operation performed per-pixel (shift, integer arithmetic, float etc.):
-- the iterated (3.6 million times) Bitmap.writePixel() takes about 5 seconds, 
-- the iterated Bitmap.readPixel() takes about 3..4 seconds, 
-- and the iteration itself with very little done 1..2 seconds, perceptually. 

But it is strange: to render the PDF pages a bitmap must be created, its pixels must be written there 3.6 million times per page, and with calculations performed per pixel... But it does not take 10+ seconds! Where is the trick?

**Comment by m-dp** [comment]
I benchmarked it: 
the **_createContrast()_** method takes, in real practice (on a device slow by design), an average of **8,200**ms; 
-- without the Bitmap.writePixel() call (commented), it takes 4,600ms, so the **_Bitmap.writePixel()_** calls take collectively **3,600**ms; 
-- without the Bitmap.readPixel() call (replaced with a constant) it takes 1,300ms, so the **_Bitmap.readPixel()_** calls take collectively **3,300**ms and the mere iteration with **_computations_** (floating point arithmetic, conditionals etc.) of createContrast() take **1,300**ms (which could improved but is not bad). 

As written, rendering take much less for the real PDF page. I am not sure how this magic happens, since in any case I would say that a 3.6 megapixel big bitmap is filled with data - yet, even if that took 3.6 seconds (but I did not measure how long it takes to render a page without using the contrast function), the calculation of the contents would be _really_ fast.

**Comment by m-dp** [comment]
I have one solution. 
The data interpolation can be done, at least, in /org/ebookdroid/droids/mupdf/codec/MuPdfPage.java , near the end of the method, before 
`        b.getBitmap().setPixels(bufferarray, 0, width, 0, 0, width, height); return b; `
There, the data is still in `bufferarray`, an array of int. 
Interpolation there is very fast - you avoid the Bitmap.readPixel() and Bitmap.writePixel() . 
I already tested it, although I do not yet have a good quick interpolation function (although a modification of the original would be good already).

**Comment by m-dp** [comment]
By the way: I also wanted to ask you 'Where did you put the "Invert"?', and I now see it's there 
```
                    if (!AppState.get().isInvert) {
                        color = ~color;
                    }
```
in _/org/ebookdroid/droids/mupdf/codec/MuPdfPage.java_ , near where I was pointing: it confirms that this should be the correct position.

**Comment by m-dp** [comment]
Done, implemented, tested; 
I suggest that you include a method 

```
	public static void QuickContrast( int[] arr , int light ){
		int threshold_lower = 0x40 + light;
		int threshold_upper = threshold_lower+0x7F;
		
		for (int i=0; i<arr.length; i++){
			int pixel = (arr[i] & 0x00FF0000)>>16;
					
		    if (pixel > threshold_upper) {
		    	arr[i]=0xFFFFFF;
		        continue;
		    }
		    if (pixel < threshold_lower ) {
		    	arr[i]=0;
		        continue;
		    }
		    pixel = (pixel-threshold_lower)<<1;
		    arr[i] = (pixel<<16) + (pixel<<8) + pixel;
		}
		
	}
```

that is called on that bufferarray in _/org/ebookdroid/droids/mupdf/codec/MuPdfPage.java_ , and you could have three options such as "Contrast, lighter", "Contrast", "Contrast, darker", equivalent for example to `QuickContrast( int[] arr , 16 );`, `QuickContrast( int[] arr , 0 );`, `QuickContrast( int[] arr , -16 );`.

**Comment by m-dp** [comment]
It is also nice to have both 2x contrast and 1.5x contrast. 
Here is the updated method: 

```
	public static void QuickContrast( int[] arr , boolean half_contrast, int light ){
		if (half_contrast){
			# 1.5x contrast
			int threshold_lower = 0x2A + light;
			int threshold_upper = threshold_lower+0xAA;
			
			for (int i=0; i<arr.length; i++){
				int pixel = (arr[i] & 0x00FF0000)>>16;
						
			    if (pixel > threshold_upper) {
			    	arr[i]=0xFFFFFF;
			    }else if (pixel < threshold_lower ) {
			    	arr[i]=0;
			    }else{
				    pixel = pixel-threshold_lower;
			    	pixel = ((pixel<<1)+pixel)>>1;
				    arr[i] = (pixel<<16) + (pixel<<8) + pixel;
			    }
			}
		}else{
			# 2x contrast
			int threshold_lower = 0x40 + light;
			int threshold_upper = threshold_lower+0x7F;
			
			for (int i=0; i<arr.length; i++){
				int pixel = (arr[i] & 0x00FF0000)>>16;
						
			    if (pixel > threshold_upper) {
			    	arr[i]=0xFFFFFF;
			    }else if (pixel < threshold_lower ) {
			    	arr[i]=0;
			    }else{
				    pixel = (pixel-threshold_lower)<<1;
				    arr[i] = (pixel<<16) + (pixel<<8) + pixel;
			    }
			}
		}
	}
```
so you can have the variants of 1.5x contrast and 2x contrast, and of making it lighter and darker (values of ±0x10 or ±0x18 are in my opinion reasonable for the lightness variation). 
You could have a dialogue for the options, or even a menu, since the options are not many 
* contrast 1.5x, 
* contrast 1.5x lighter, 
* contrast 1.5x darker, 
* contrast 2x, 
* contrast 2x lighter, 
* contrast 2x darker

**Comment by foobnix** [comment]
Thank you for help with contrast and new algorithm, I will add it on Monday
evening and we test your implementation.
A am also want to add contrast live preview and individual book
configuration.

8 окт. 2017 г. 17:44 пользователь "m-dp" <notifications@github.com> написал:

**Comment by m-dp** [comment]
My pleasure! I wish I could contribute more

**Comment by m-dp** [comment]
One further note: the code above only uses the red channel, but a composition of the three channels can be quickly done; the retrieval of the luminosity at the beginning of the loops becomes: 
`int pixel = ((arr[i] & 0x00FF0000)>>17) + ((arr[i] & 0x0000FF00)>>10) + ((arr[i] & 0x000000FF)>>2);`
which is, two parts red, one part green and one part blue. 
The method as written above (16:44) takes around **110**ms to complete for 1.8 megapixels (one page of the two displayed) on slow devices; it takes around **145**ms with this modification that uses all channels. I think 150ms is very affordable - also considering that it means 10ms or 20ms on fast devices.

**Comment by foobnix** [comment]
I have update contrast algorithm with preview
1) Your algorithm not works (i don't know why, you can create android demo and verify)
2) I have modify my algorithm by your feedback and increase speed
a) it's works with array in MupdfPage
b) it's calculate only R channel (I found this algorithm on stackoverflow and don't know how it works)

public static void quickContrast1(int[] arr, double light) {
        double contrast = Math.pow((100 + light) / 100, 2);
        int R;
        for (int i = 0; i < arr.length; i++) {
            int pixel = arr[i];

            if (pixel == Color.WHITE) {
                continue;
            }
            if (pixel == Color.BLACK) {
                continue;
            }
            R = Color.red(pixel);
            R = (int) (((((R / 255.0) - 0.5) * contrast) + 0.5) * 255.0);
            if (R < 0) {
                R = 0;
            } else if (R > 255) {
                R = 255;
            }
            arr[i] = Color.rgb(R, R, R);
        }
    }

**Comment by m-dp** [comment]
Maybe I was not clear in my text, my algorithm is working well on a modified Librera on my tablet... And it took me some time to make it work well!  ; )

The position to call is correct (where you have  `if (AppState.get().contrast != 0) { [...]` )

Are you calling the method in this way? 

```
QuickContrast( bufferarray , true  ,   0 );     //contrast 1.5x,
QuickContrast( bufferarray , true  , -24 );     //contrast 1.5x lighter
QuickContrast( bufferarray , true  ,  24 );     //contrast 1.5x darker
QuickContrast( bufferarray , false ,   0 );     //contrast 2x,
QuickContrast( bufferarray , false , -24 );     //contrast 2x lighter
QuickContrast( bufferarray , false ,  24 );     //contrast 2x darker
```

The method, using all channels: 
```
    public static void QuickContrast( int[] arr , boolean half_contrast, int light ){
        if (half_contrast){
            // 1.5x contrast
            int threshold_lower = 0x2A + light;
            int threshold_upper = threshold_lower+0xAA;
            
            for (int i=0; i<arr.length; i++){
                int pixel = ((arr[i] & 0x00FF0000)>>17) + ((arr[i] & 0x0000FF00)>>10) + ((arr[i] & 0x000000FF)>>2);
                        
                if (pixel > threshold_upper) {
                    arr[i]=0xFFFFFF;
                }else if (pixel < threshold_lower ) {
                    arr[i]=0;
                }else{
                    pixel = pixel-threshold_lower;
                    pixel = ((pixel<<1)+pixel)>>1;
                    arr[i] = (pixel<<16) + (pixel<<8) + pixel;
                }
            }
        }else{
            // 2x contrast
            int threshold_lower = 0x40 + light;
            int threshold_upper = threshold_lower+0x7F;
            
            for (int i=0; i<arr.length; i++){
                int pixel = ((arr[i] & 0x00FF0000)>>17) + ((arr[i] & 0x0000FF00)>>10) + ((arr[i] & 0x000000FF)>>2);
                        
                if (pixel > threshold_upper) {
                    arr[i]=0xFFFFFF;
                }else if (pixel < threshold_lower ) {
                    arr[i]=0;
                }else{
                    pixel = (pixel-threshold_lower)<<1;
                    arr[i] = (pixel<<16) + (pixel<<8) + pixel;
                }
            }
        }
    }
```

The explanation of the algorithm is: 

-- we assume that the _bufferarray_ is an array of integers of format ARGB (tested and it is true); so, _this_integer_  & 0x00FF0000 = red , _this_integer_  & 0x0000FF00 = green , _this_integer_  & 0x000000FF = blue .

-- each channel value can range from 0 (darkest) to 255 (brightest). To make things quick one can take channel Red (green is too bright, blue is too dark); but it is also easy and fast to compose red, green and blue as follows: 
2 x Red/4 + 1 x Green/4 + 1 x Blue/4
which in fast "shift" arithmetic is `int pixel = ((arr[i] & 0x00FF0000)>>17) + ((arr[i] & 0x0000FF00)>>10) + ((arr[i] & 0x000000FF)>>2);` (red is taken from the integer, shifted right by 16 bits to have it as a byte, multiplied by four and divided by two which means again shifted right by one bit; green is shifted right by 8 bits to have it as a byte, then divided by four which means shifted right by 2 bits, and blue is already in the right position to be a byte and it is divided by four being shifted right by 2 bits). 

-- to create the contrast, we take a section of the range (say, between 64 and 192) that we expand to the full range of 0 to 255. What is below 64 will be black (0); what is above 192 will be white (255). To do that expansion, you can do `(value - 64)*2`, or in the code `pixel = (pixel-threshold_lower)<<1;`

-- to create back a ARGB integer, we use the `arr[i] = (pixel<<16) + (pixel<<8) + pixel;` which is equivalent to "red*65536 + green*256 + blue", and our red=green=blue because we only need "black greys and white". 

-- also, I add the ability to shift the range to have brighter or darker effect - if instead of 64 to 192 I take 48 to 176 it will be lighter; if I take 80 to 208 it will be darker. The main need for "contrast" is with PDF of scanned pages; scanners can not only have reduced contrast but also too-dark or too-bright effect. So we can correct it. 

-- the above comments are for the "2x contrast"; the "1.5x contrast" is similar, but the picked range is of 170 values instead of 128 values, and the "expansion" of that picked range to the full range is by doing "((pixel*2)+pixel)/2" (which is pixel = `((pixel<<1)+pixel)>>1;`)

**Comment by foobnix** [comment]
I agree your function works :)
But my function quickContrast1 also now works very fast and show good result.

>> my algorithm is working well on a modified Librera on my tablet.
it's very good, maybe you can compare quickContrast1 and  quickContrast from the MagicHelper.

As for me quickContrast1 also very good now

**Comment by m-dp** [comment]
Excellent, I'll compare them on Saturday... 
If you do not mind, I may propose a few optimizations for quickContrast1, as soon as I am back to the desktop

**Comment by foobnix** [comment]
Please optimize, I do not mind.

**Comment by m-dp** [comment]
I have it : )

The below method applies a variation in both contrast and brightness and takes a mere **97ms** on "slow" i.MX 6SoloLite devices for 1.8 megapixel images. 

We did not notice that there are only 256 possible inputs  : ) (I realized that when I saw you caching the last value through variables pixedCache and pixedResultCache.) Hence, the most rational method appears now to me to use an array to map the input and the possible outputs. The creation of such array, that maps inputs from 0 to 255 to their correspondence after transformation through brightness and contrast, takes less than 1ms. Application of that map to the whole 1.8 million elements of the image array, less than 100ms. 

The parameters: 
**_extra_contrast_**, when 0 does not change contrast, when 100 doubles contrast;
**_delta_brightness_**, should reasonably be between -100 an +100 (and will probably be useful between -20 and +20). 

The below method is tested - I injected it in version 7.2.20 (arm).  

```
public static void quickContrast2(int[] arr, int extra_contrast, int delta_brightness) {
    int lum;
    
    // Use linear contrast variation; extra_contrast=0 = no change, extra_contrast=100 = 2x contrast 
    double contrast = (100 + extra_contrast) / 100.0;
    
    int[] brightnessContrastMap = new int[256];
    // each of the 256 values we can read is mapped to the output values we will write
    for (int i=0; i<256; i++){
        lum = i;                                  // take the input
        lum = lum-delta_brightness;               // apply brightness variation
        lum = (int)(((lum-128)*contrast)+128);    // apply contrast
        if(lum<0){                                // flatten excess
            lum=0;
        }else if(lum>255){
            lum=255;
        }
        brightnessContrastMap[i] = (lum<<16) + (lum<<8) + lum;    // compose greyscale
    }
    
    // process the real image
    for (int i = 0; i < arr.length; i++) {
        // Get luminosity. Also use G and B, with 2x R 
        int temp = arr[i]; 
        lum = ((temp & 0x00FF0000)>>17) + ((temp & 0x0000FF00)>>10) + ((temp & 0x000000FF)>>2);
        // retrieve output from map 
        arr[i] = brightnessContrastMap[lum];
    }

}
```

**Comment by m-dp** [comment]
One note: I did not like defining the contrast as `Math.pow((100 + light) / 100, 2)` , because the input value to double the contrast would be 42, to triple it 73... It is more "universal" to have a "100 increase" for double, 200 for triple etc. Also, I do not see a special need to use this curve, linear is fine. 
For the rest, it follows the logic of your algorithm but optimizes in general, by dividing the steps of the calculation of the small map and its application to the large input array, and in detail, by polishing small things. 
Also, I used the fast composition of all channels instead of just red - just to be sure, in case the source has unusual channels. 
And of course, I added the brightness control, which is very useful (applying only contrast does not necessarily nail the point where text is most readable).

**Comment by foobnix** [comment]
I have added to the beta your crazy fast algorithm  :)
Please test and verify...

**Comment by m-dp** [comment]
I think it works very well! I tried it with scanned .pdf (the target), but also with raster+vector "publishing" pdf, and with EPUB. 
As planned, will you make the setting per-book, individual for every document, instead of the current global setting? 
By the way: the "test page", that you initially placed with the contrast setting interface, was a good idea... Probably the best idea is to have the pages present during normal reading mode change in real time (with a small 1 second delay in order to collect the users changes to the sliders) under the brightness/contrast control interface?

**Comment by m-dp** [comment]
I add a bit of (psuedo)code to clarify what I meant with "with a small 1 second delay in order to collect the users changes to the sliders". There are probably better ways to do it - maybe classes already exist...

```
private SomeTimer someTimer;
private boolean isUpdatePending=false;
private long lastBaseTimeStamp=0;

// Receive the event that the GUI sliders have changed 
SomeListener someListener = new SomeListener() {
	// [...]
	// Whenever the settings are changed, set that changes will be computed some time from NOW, where "now" = lastBaseTimeStamp. 
	lastBaseTimeStamp = (int) System.currentTimeMillis();
	if(!isUpdatePending){
		// Every once in a while, we check if our buffer period has passed
		someTimer.schedule( new CountDownToUpdate(), 200);
	}
};

class CountDownToUpdate extends TimerTask {
	@Override public void run(){
		MainActivity.this.runOnUiThread(
			new Runnable(){
				@Override public void run(){
					long currentTimeStamp = System.currentTimeMillis();
					long elapsed = currentTimeStamp-lastBaseTimeStamp; 
					if (elapsed>900){
						isUpdatePending=false;
						// ok, one second from last input has passed, let's do our magic
						okLetsDoOurMagic();
					}else{
						// otherwise, we will check again in a while
						someTimer.schedule( new CountDownToUpdate() , 200 );
					}
				}
			}
		);
	}
}
```

**Comment by foobnix** [comment]
I will add individual settings for books later

**Comment by foobnix** [comment]
Could you please write me on email I have an idea and want to discuss with you.

**Comment by foobnix** [comment]
implemented in beta
