### ISSUE TITLE
Better customization of the grid of books

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#3]
In the preferences, "Cover image size" section, it would be nice that: 
- the "Grid [size]" and "Column count" do not necessarily modify each other; 
- a checkbox "Auto adjust" is used to have current behaviour of relation of "Cover image size in grid" and column count; 
- the cover image size still cannot be more than (screen size / column count); 
- but if the cover image size is small (e.g. 80), and the columns large (e.g. count = 4), good, the grid shows a small cover, but with large text strings (title, filename etc.), and the grid rows are short proportionally to the cover image size (instead of tall); 
- also, a checkbox could "hide the cover": in this case, * the column count determines the column width, * the cover size determines the column height (the same as if the cover was displayed), and * the text screen occupy the space instead of the cover page, and they word wrap.

**Comment by m-dp** [comment]
Alternatively: 
- you could add "Row count" along with the existing "Column count"
  - in case of switch to landscape to portrait, "Row count" and "Column count" swap - 5x3 when landscape becomes 3x5 when portrait (the division of the screen in cells does not change, the cells remain the same, only the orientation of what is inside the cells (text, images, controls) changes)
- depending on the space that is left on the cell when placing the "cover-page thumbnail", the text strings (title, filename etc.) can go either below the cover-page thumbnail or on its right 
- a checkbox could "hide the cover", and only the text strings (title, filename etc.) remain in the cell. 

This should provide the most flexibility in the visual rendering of the documents collection. 
In my view, I like to keep the full filename visible, but wasting as little screen as possible - legible grids with as many titles as possible, wasting little space. 

Another note - I see that you are using space-dash-space, ' - ', as a separator to divide fields (e.g. author vs. title) in the filename. I wish to note that using the dash that way is not universal. For example, I use that sequence to divide fields like 'title - subtitle [author - publisher]'. It would be advanced, but maybe you could specify a field in the preferences to specify what to use as a separator; you are now using ' - ' but in my case it would be ' [' (or '' to disable the feature).

**Comment by m-dp** [comment]
...also a grid view with the same layout of the "List", just adding more columns, would be nice. It could help to have a checkbox only display the filename and not the title:  the title is often redundant. 

I see that the "starred" view only allows the List: could we also have the option of a grid there?

**Comment by foobnix** [comment]
You write to more suggestions, it would be good if you choose the most wanted 3 ideas and create separate 3 new issues with details and marks on screenshots also . It's will be more informative and more clear for me what to do.
Thank you for help

**Comment by foobnix** [comment]
One idea = one issue
