### ISSUE TITLE
Do you plan to migrate to Android Studio ?

### ISSUE THREAD

**Issue by chihung93** [foobnix/LirbiReader#30]
Hello, I've a question : 
Do you plan to migrate to Android Studio?
Tks .

**Comment by foobnix** [comment]
Yes but for me AS is not so good as Eclispe.
I don't know when but migration to Studio will be exactly.

1 лист. 2017 р. 18:43 "Sammy" <notifications@github.com> пише:

**Comment by chihung93** [comment]
I tried migrating to the Android Studio, and it works fine.
You can check my repository here: 
https://github.com/chihung93/LirbiReader

Tks.

**Comment by chihung93** [comment]
I often see other applications will have multiple files .so for different architectures.
But in this app I only see 2 architectures (x86 and armeabi-v7a), so 
Can other devices use the different architectures to run?

<img width="432" alt="screen shot 2017-11-02 at 11 59 48 am" src="https://user-images.githubusercontent.com/5199109/32310507-5e1e8b3e-bfc5-11e7-81fd-16a5fbae40b6.png">

**Comment by foobnix** [comment]
yes, other devices can run x86 or arm-v7 - it's compatible.
I am surprised Android Studio can easy convert, maybe it my change to migrate to it.
