### ISSUE TITLE
Load epub very slowly ?

### ISSUE THREAD

**Issue by chihung93** [foobnix/LirbiReader#34]
I try to read this book
Name of Book: reactive-programming-with-rxjava-tomasz-nurkiewicz.epub 
Size: 5.8 MB
Total pages: 1488
But it displays the progressBar and loads for a long time.

**Comment by chihung93** [comment]
I think it related to load an image in .epub. Maybe should upgrade Universal Image Loader or use Glide/Piscaso

**Comment by chihung93** [comment]
Possible cause is because mupdf reads slow epub.

**Comment by foobnix** [comment]
we know but can't make faster because using mupdf engine

**Comment by ijustknow** [comment]
It is true that Epub loads very slow, slower than PDF converting to Epub.
Is it possible to add another framework for Epub?

**Comment by chihung93** [comment]
@ijustknow I think we'll integrate another framework for epub in this libs.
