### ISSUE TITLE
ODPS server with basic authentication issue

### ISSUE THREAD

**Issue by X-Ryl669** [foobnix/LirbiReader#38]
I have an ODPS server with HTTP basic authentication that's working fine with FBReader and iReader.
With Librera, there are 2 issues:

1. When I set up the password, it's displayed in clear text in the server's list (not really wanted)
2. The system never succeeding connecting to the server and thus prevent any action, popping up error dialog endlessly, I have to force close it. I've modified my server not to use authentication, and it's not breaking the crazy loop.

Thanks for support

**Comment by foobnix** [comment]
Could you please provide the OPDS server url

**Comment by X-Ryl669** [comment]
Sent to your (profile) email.

**Comment by foobnix** [comment]
Librera only support basic authorization
https://en.wikipedia.org/wiki/Basic_access_authentication
it's look like on your site is other one

**Comment by X-Ryl669** [comment]
Next beta should also support Digest authentication.
