### ISSUE TITLE
Can you export file .so in Github or move all source code via Android Studio for easy use and build .so files?

### ISSUE THREAD

**Issue by chihung93** [foobnix/LirbiReader#39]
Hello Ivan Ivanenko,

Can you export file .so to Github or move all source code via Android Studio for easy use and build .so files?
Because most of the Android dev have switched to Android Studio because Eclipse is no longer supported, so it is very difficult for me to use your library for further development and fix bugs.

Thank you for your contribution to the open source community.

**Comment by foobnix** [comment]
Hello,
I can't help you with AS, 
You can see help in the issue
https://github.com/foobnix/LirbiReader/issues/30
