### ISSUE TITLE
Is android studio suppored?

### ISSUE THREAD

**Issue by Hardy311t3** [foobnix/LirbiReader#59]
Guys you are doing greate job and i was actually for some good project like other then fbreader which is not update from long time (one that is open sourced). So just had look on to librera project and as i far as i can see it is continually being developed with interesting features. So have couple questions.

I want to use librera in my open source project as it is under gpl 3.
So, if yes then is Android studio supported for the project or if not
Then is there any better readme/Documentation Available.

Response from your end would be appreciated.

And thanks for such a great contribution to the community.

**Comment by foobnix** [comment]
Hi, at this moment we don't support  AS but have a plan to migrate for it in future.
