### ISSUE TITLE
Colour of default book covers

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#6]
In case a book does not have a cover (the first page of a PDF, etc.), the software creates a cover by placing a default bitmap, colourizing it, and writing the title on it. 

Problem: unrelated random-like colours can be confusing. For example, "The big book, Part 1" in dark brown, "The big book, Part 2" in light blue, "Some other book" in blue. This is messy. 

Proposal: the colorization of the book cover uses a default colour (a neutral colour like grey), 
but (secondary proposal) the user may assign a different colour to a single book cover from an editable palette, to allow for categorization. 

Example: all default covers (those which must be built using the default image with the cursive "L") are grey, but the user has set that "The big book, Part 1" and "The big book, Part 2" are colourized using (say) the fifth colour of the covers palette, say light blue, because that colour represents to the user a category for those books.

(Lower priority)

**Comment by foobnix** [comment]
I like different cover icons.
What do yo think if link color of cover to the file name first letter.
For example, all book starts with A will have the same cover in day and night mode every time.

**Comment by foobnix** [comment]
How do you know I also think so :))
Will be in beta today evening (by Kyiv time)

6 сент. 2017 г. 11:55 пользователь "m-dp" <notifications@github.com>
написал:

**Comment by m-dp** [comment]
Clever people exchange tricks but think alike  ; D

**Comment by foobnix** [comment]
fixed
