### ISSUE TITLE
Do The project supported in Android studio?

### ISSUE THREAD

**Issue by Hardy311t3** [foobnix/LirbiReader#66]
Great project guys a nice combo of popular and powerful projects and as it in continuous development it will definitely help a lot of devz and take over project like fbreader as open source fbreader is not being developed any more so yeah Librera will definitely help alot of people's to speedup the job

BUT, as you mentioned it require Eclipse so the issue is now a days we all are using android studio for all of our project so, ether if you can Add some better documentation on this or If it is possible to migrate from eclipse to Android studio that would be great.

And Thanks for such a great contributions to open source community.

Keep up the Good work.

**Comment by foobnix** [comment]
Hello 
I am old school  Android developer and prefer Eclipse and custom scripts.
You can find more info on this blog http://blog.vogella.com/tag/adt/
Maybe in future I can migrate to Android Studio.

Ivan
