### ISSUE TITLE
Scanned pdf reflow

### ISSUE THREAD

**Issue by ijustknow** [foobnix/LirbiReader#69]
Reflow does not work for scanned PDF file.

**Comment by foobnix** [comment]
yes, but result will be the same like pdf

**Comment by ijustknow** [comment]
When I say it does not work, i mean it shows well, but you cannot resize the font, which makes the book unreadable. The meaning of reflow I think is to make it readable.

**Comment by ildar** [comment]
"Scanned" word may be misleading. Would you please look how the Reflow function works in apps: MuPDF (Lightweight document viewer) - https://f-droid.org/app/com.artifex.mupdfdemo or in Book Reader (Simple book reader) - https://f-droid.org/app/com.github.axet.bookreader ?
Thanks!
