### ISSUE TITLE
 Better customization of the grid of books (consolidated proposal)

### ISSUE THREAD

**Issue by m-dp** [foobnix/LirbiReader#7]
**NOTE**: _heavily edited, last edits in the night between Sat 2 and Sun 3 Sep_.

Browsing the documents, one can currently use a grid view of the books; it is configured through parameters "Cover image size" and "Column count". The text (title, filename etc.) is placed below the book cover image. 

Problem: if the cover size is small, the strings below are too short, but if the cover is large, and the text is long, few documents per screen are visible. 

Proposal: to have a more compact grid view, which allows to see more books per screen: 
* another "view mode" named something like 'Compact' alongside with 'List', 'Grid' and 'Cover' is added to the relevant pop-up menu; 
* if the "compact mode" is on, then "Cover image size" is irrelevant: the book cover image is set to dimensions based on 80dip (80x120 ?); 
* "Column count" decides the number of columns;
* The text - the filename only - is placed to the right of the book cover image; 
* At least the "starred" and "menu" icons are below the filename. 

Below is an example, using "Column count" = 4: 

![compactgrid](https://user-images.githubusercontent.com/11769458/29989017-c063226c-8f70-11e7-97ed-506c6b976f95.png)

**Comment by m-dp** [comment]
Some small modifications to browse_item_grid.xml already take us almost there: 
setting '_android:visibility="gone"_' to the FrameLayout that contains the cover and 
setting android:layout_width="fill_parent" to the LinearLayout that contains the text produces the following compact grid: 

![librera_compact_grid2](https://user-images.githubusercontent.com/11769458/29994580-0ca4531e-8fd3-11e7-8a59-25ec62b6411c.jpg)

But (as per the issue description above of yesterday):
-- in this view, space is better used if the text uses only filenames (to split in more fields like author and title wastes space); 
-- there is still enough space for the book cover. Note: contrary to what posted in the issue description above of yesterday, maybe _the "Cover image size" is not needed_: the text part (the '_android:id="@id/layoutBootom"_') already is set to a minimum size of '_android:layout_height="80.0dip"_', so just making for the book cover a thumbnail of fixed size, height = 64.0dip, is enough.

**Comment by m-dp** [comment]
I am quite content with this aspect for a "Compact" visualization, which in my tests replaces the "Grid" visualization: 
-- The xml of the cell has a few modifications over the original - the horizontal orientation, the width filling the grid making all cells evenly wide, and small modifications to the text side - height, padding and line spacing: 
[browse_item_grid.xml.zip](https://github.com/foobnix/LirbiReader/files/1279221/browse_item_grid.xml.zip)
-- The book cover image has variable size, but it is taken as the coverSmallSize (that of the "List" visualization) instead of the coverBigSize (FileMetaAdapter.java); 
-- I place the filename as the "title1" if the "author" is not defined or just guessed from the filename syntax (I provisionally disabled the heuristic in TxtUtils.smali); 
-- I set three lines for "title1" when displaying the filename (no author) or two lines otherwise (again in FileMetaAdapter.java). These hardcoded values are correct for a book cover width (coverSmallSize) of 56dip, as in the image below; it should probably be more correct to calculate them: 
empirically: 
title1_lines = (int)( 480 / ( (screen_width_dip / num_columns ) - coverSmallSize - 16 ) )

![compact3a](https://user-images.githubusercontent.com/11769458/30087207-9f390520-929f-11e7-821c-d23ce8c49928.jpg)

**Comment by foobnix** [comment]
Added compact mode to the beta 7.1.7
Column count in the compact mode will be "column count" / 2
For example in the grid mode 6 but in the compact mode will be 3 columns
if you make cover size for easy mode small then title and author will disappear in compact mode.

**Comment by m-dp** [comment]
I have not seen the effect yet (as the beta is not uploaded, and I have not read fully the code changes); 
if I have understood your logic well: (if you are still using "coverBigSize") have you considered that you could both enlarge the columns and reduce the image? So, if you double the width of the column, and halve the width of the image, you have shorter rows which allow for more titles in the page.

**Comment by m-dp** [comment]
I just tried it - sorry I was away: it is very, very good! 
(I did not fully understand earlier - I see that you used "coverSmallSize", or the "List cover", instead of the "coverBigSize", or the "Grid cover", as per my proposal, so what I wrote above on 6 Sep about the reducing the big image is of course not needed.)

I wish to note two things: 
-- there is an effect of "excessive right padding" on the text (I cannot see the reason immediately in the .xml), please see this screenshot: 

![excessive_padding](https://user-images.githubusercontent.com/11769458/30237669-35620a58-9537-11e7-8d86-ec2cf32c6b89.jpg)

-- there is no mode selection in the "Starred" tab it would be nice and consistent to have it. I will add this to the Issues, for order. 

Great job!

**Comment by m-dp** [comment]
About the padding in the .xml, which is the division in three columns (image|text|menu), I think browse_item_list.xml should be more like this (tested and works, but please check it if you wish to use it): 
[browse_item_list.xml.zip](https://github.com/foobnix/LirbiReader/files/1289600/browse_item_list.xml.zip)

By the way: I tried using three lines, as in _holder.title.setLines(3)_ instead of _holder.title.setLines(2)_, in
/com/foobnix/ui2/adapter/FileMetaAdapter.java
and I think it is not bad... Have you tried it?

**Comment by foobnix** [comment]
Please verify title width.
I have also added command to hide all images in the list.
Try to input to the search input
"@cmd_images_on_off"

9 сент. 2017 г. 10:21 пользователь "m-dp" <notifications@github.com>
написал:

About the padding in the .xml, which is the division in three columns
(image|text|menu), I think browse_item_list.xml should be more like this
(tested and works, but please check it if you wish to use it):
browse_item_list.xml.zip
<https://github.com/foobnix/LirbiReader/files/1289600/browse_item_list.xml.zip>

By the way: I tried using three lines, as in *holder.title.setLines(3)*
instead of *holder.title.setLines(2)*, in
/com/foobnix/ui2/adapter/FileMetaAdapter.java
and I think it is not bad... Have you tried it?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/foobnix/LirbiReader/issues/7#issuecomment-328260360>,
or mute the thread

**Comment by foobnix** [comment]
I hope fixed
