### ISSUE TITLE
Feature request: proportional auto-scroll speed

### ISSUE THREAD

**Issue by dfelippa** [foobnix/LirbiReader#89]
The problem: 
scroll speed is constant no matter how much text is on the screen. Sometimes paragraphs are short. Sometimes are long. Sometimes there is a large space between paragraphs and sometimes they are cluttered. Sometimes there are images, and finally there is the spacing  between pages. This happens within a single text.

Feature request:
It would be great if the auto-scroll speed was proportional to the amount of words (or characters) shown on the screen. 
So when there is a lot of text on the screen scroll speed would be proportionally slower, while when there are few words on the screen it would be proportionally faster.

This would really help a lot!

**Comment by foobnix** [comment]
Very interesting idea, but it's not possible in nearest future.
